name: 'Install Azure CLI'
description: 'Install Azure CLI'
runs:
  using: 'composite'
  steps:
    - name: uninstall azure-cli
      shell: bash
      run: |
        sudo apt-get remove -y azure-cli

    - name: install azure-cli 2.61.0
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_DIST=$(lsb_release -cs)
        echo "Types: deb
        URIs: https://packages.microsoft.com/repos/azure-cli/
        Suites: ${AZ_DIST}
        Components: main
        Architectures: $(dpkg --print-architecture)
        Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources
        sudo apt-get update
        sudo apt-get install azure-cli

        apt-cache policy azure-cli
        # Obtain the currently installed distribution
        AZ_DIST=$(lsb_release -cs)
        # Store an Azure CLI version of choice
        AZ_VER=2.61.0
        # Install a specific version
        sudo apt-get install azure-cli=${AZ_VER}-1~${AZ_DIST} --allow-downgrades
