name: Build AWS AMI
description: Builds the AMI for AWS private operators

inputs:
  identity_scope:
    description: The identity scope [uid2, euid]
    required: true

runs:
  using: "composite"

  steps:
    - name: Build EIF
      id: buildEIF
      shell: bash
      run: |
        make -f Makefile.nitro ${{ inputs.identity_scope }}operator.eif
        docker cp amazonlinux:/${{ inputs.identity_scope }}operator.eif ./build/${{ inputs.identity_scope }}operator.eif

    - name: Show PCR0
      id: showPCR0
      shell: bash
      run: |
        PCR0=$(nitro-cli describe-eif --eif-path ${{ inputs.identity_scope }}operator.eif | jq -r '.Measurements.PCR0' | xxd -r -p | base64)
        echo "PCR0: " $PCR0
        echo "PCR0=$PCR0" >> $GITHUB_OUTPUT

    - name: Set identity scope
      id: setIdentityScope
      shell: bash
      run: |
        echo "${${{ inputs.identity_scope}}@u}" >> ./build/identity_scope
