name: Build AWS EIF
description: Builds the EIF for AWS private operators

inputs:
  identity_scope:
    description: The identity scope [uid2, euid]
    required: true
  artifacts_base_output_dir:
    description: The base output directory for the AMI artifacts
    required: true

runs:
  using: "composite"

  steps:
    - name: Create build folder
      shell: bash
      run: |
        mkdir -p build/

    - name: Set identity scope
      shell: bash
      run: |
        echo "${{ inputs.identity_scope }}" | tr '[:lower:]' '[:upper:]' >> ./build/identity_scope

    - name: Build EIF
      shell: bash
      run: |
        make -f Makefile.nitro ${{ inputs.identity_scope }}operator.eif
        docker cp amazonlinux:/${{ inputs.identity_scope }}operator.eif ./build/${{ inputs.identity_scope }}operator.eif

    - name: Show PCR0
      shell: bash
      run: |
        PCR0=$(nitro-cli describe-eif --eif-path ${{ inputs.identity_scope }}operator.eif | jq -r '.Measurements.PCR0' | xxd -r -p | base64)
        echo "PCR0: ${PCR0}"
        echo "PCR0=${PCR0}" >> ${GITHUB_OUTPUT}

    - name: Prepare artifacts
      shell: bash
      run: |
        ARTIFACTS_OUTPUT_DIR="${{ inputs.artifacts_base_output_dir }}/${{ inputs.identity_scope }}"
        mkdir -p ${ARTIFACTS_OUTPUT_DIR}
        cp ./dante-1.4.3/sockd/sockd                        ${ARTIFACTS_OUTPUT_DIR}/
        cp ./build/${{ inputs.identity_scope }}operator.eif ${ARTIFACTS_OUTPUT_DIR}/
        cp ./build/identity_scope                           ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/start.sh                           ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/stop.sh                            ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/proxies.host.yaml                  ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/sockd.conf                         ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/uid2operator.service               ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/pipeline/VERSION                   ${ARTIFACTS_OUTPUT_DIR}/
        cp ./uid2-aws-enclave-vsockproxy/build/vsock-bridge/src/vsock-bridge ${ARTIFACTS_OUTPUT_DIR}/vsockpx
