name: Build AWS EIF
description: Builds the EIF for AWS private operators

inputs:
  identity_scope:
    description: The identity scope [uid2, euid]
    required: true
  artifacts_base_output_dir:
    description: The base output directory for the AMI artifacts
    required: true

outputs:
  enclave_id:
    description: The enclave id for this EIF.
    value: ${{ steps.prepare_artifacts.outputs.enclave_id }}
    
runs:
  using: "composite"

  steps:
    - name: Run amazonlinux Docker image
      shell: bash
      run: |
        docker build -t amazonlinux -f ./scripts/aws/pipeline/amazonlinux.Dockerfile .
        docker run -d --privileged --name amazonlinux amazonlinux:latest

    - name: Create build folder
      id: buildFolder
      shell: bash
      run: |
        BUILD_FOLDER="./build/${{ inputs.identity_scope }}"
        mkdir -p $BUILD_FOLDER
        echo "BUILD_FOLDER=$BUILD_FOLDER" >> $GITHUB_OUTPUT

    - name: Get identity scope
      shell: bash
      run: |
        echo "${{ inputs.identity_scope }}" | tr '[:lower:]' '[:upper:]' > ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/identity_scope.txt
        cat ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/identity_scope.txt

    - name: Get version number from pom.xml
      shell: bash
      run: |
        grep -o '<version>.*</version>' ./pom.xml | head -1 | sed 's/<version>\(.*\)<\/version>/\1/' > ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/version_number.txt
        cat ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/version_number.txt

    - name: Build EIF
      shell: bash
      run: |
        make -f Makefile.nitro ${{ inputs.identity_scope }}operator.eif

    - name: Prepare artifacts
      id: prepare_artifacts
      shell: bash
      run: |
        ARTIFACTS_OUTPUT_DIR="${{ inputs.artifacts_base_output_dir }}"

        mkdir -p ${ARTIFACTS_OUTPUT_DIR}

        cp ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/identity_scope.txt                                       ${ARTIFACTS_OUTPUT_DIR}/
        cp ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/version_number.txt                                       ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/start.sh                                                                                 ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/stop.sh                                                                                  ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/proxies.host.yaml                                                                        ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/sockd.conf                                                                               ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/uid2operator.service                                                                     ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/pipeline/$(cat ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/identity_scope.txt)_VERSION ${ARTIFACTS_OUTPUT_DIR}/VERSION
        cp ./scripts/aws/syslog-ng/syslog-ng-server.conf                                                          ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/syslog-ng/server/syslog-ng-pubkey.gpg                                                    ${ARTIFACTS_OUTPUT_DIR}/
        cp ./scripts/aws/syslog-ng/server/syslog-ng-4.6.0-1.el7.x86_64.rpm                                        ${ARTIFACTS_OUTPUT_DIR}/

        docker cp amazonlinux:/sockd                                    ${ARTIFACTS_OUTPUT_DIR}/
        docker cp amazonlinux:/vsockpx                                  ${ARTIFACTS_OUTPUT_DIR}/
        docker cp amazonlinux:/${{ inputs.identity_scope }}operator.eif ${ARTIFACTS_OUTPUT_DIR}/uid2operator.eif

        docker cp amazonlinux:/pcr0.txt                                 ${{ steps.buildFolder.outputs.BUILD_FOLDER }}
        docker cp amazonlinux:/pcr0.txt                                 ${ARTIFACTS_OUTPUT_DIR}/
        echo "enclave_id=$(cat ${{ steps.buildFolder.outputs.BUILD_FOLDER}}/pcr0.txt)" >> $GITHUB_OUTPUT

    - name: Cleanup
      shell: bash
      run: |
        docker stop $(docker ps -a -q)
        docker system prune -f
