apiVersion: v1
kind: Namespace
metadata:
  name: compute
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-and-validator-operators-configmap
  namespace: compute
data:
  client_side_token_generate: 'true'
  client_side_token_generate_log_invalid_http_origins: 'true'
  key_sharing_endpoint_provide_app_names: 'true'
  enclave_cpu_count: '14'
  enclave_memory_mb: '40152'
  customize_enclave: 'true'
  test: test1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: operator
  name: operator-service
  namespace: compute
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    env: test
    tmp: tmp
  labels:
    app: operator
    enclave: "true"
    flavor: operator
  name: operator
  namespace: compute
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: operator
      enclave: "true"
      flavor: operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        env: test
      labels:
        app: operator
        enclave: "true"
        flavor: operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: aws-nitro-enclaves-k8s-dp
                operator: In
                values:
                - enabled
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: enclave
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
      containers:
      - image: ghcr.io/iabtechlab/uid2-operator-eks-uid2:<image_version>
        imagePullPolicy: Always
        name: operator
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 9080
          name: prometheus
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ops/healthcheck
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            aws.ec2.nitro/nitro_enclaves: "1"
            cpu: "1"
            hugepages-1Gi: 48Gi
          requests:
            aws.ec2.nitro/nitro_enclaves: "1"
            cpu: "1"
            hugepages-1Gi: 48Gi
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /ops/healthcheck
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config/config-values
          name: configmap
          readOnly: true
        - mountPath: /etc/secret/secret-value
          name: secret-volume
          readOnly: true
        - mountPath: /dev/hugepages
          name: hugepage
          readOnly: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gh-uid2-docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: configmap
        projected:
          sources:
          - configMap:
              name: operator-and-validator-operators-configmap
      - emptyDir:
          medium: HugePages-1Gi
        name: hugepage
      - name: secret-volume
        secret:
          secretName: github-test-secret
---
apiVersion: v1
kind: Namespace
metadata:
  name: nitro-enclaves
  labels:
    name: nitro-enclaves
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-nitro-enclaves-k8s-daemonset
  namespace: kube-system
  labels:
    name: aws-nitro-enclaves-k8s-dp
    role: agent
spec:
  selector:
    matchLabels:
      name: aws-nitro-enclaves-k8s-dp
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aws-nitro-enclaves-k8s-dp
      annotations:
        node.kubernetes.io/bootstrap-checkpoint: "true"
    spec:
      nodeSelector:
        aws-nitro-enclaves-k8s-dp: enabled
      priorityClassName: "system-node-critical"
      hostname: aws-nitro-enclaves-k8s-dp
      containers:
      - name: aws-nitro-enclaves-k8s-dp
        image: public.ecr.aws/aws-nitro-enclaves/aws-nitro-enclaves-k8s-device-plugin:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            cpu: 100m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 15Mi
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev-dir
            mountPath: /dev
          - name: sys-dir
            mountPath: /sys
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev-dir
          hostPath:
            path: /dev
        - name: sys-dir
          hostPath:
            path: /sys
      terminationGracePeriodSeconds: 30