apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: operator 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: operator
      annotations:
        microsoft.containerinstance.virtualnode.ccepolicy: ''
        microsoft.containerinstance.virtualnode.identity: /subscriptions/63e97a70-d825-4b08-af6d-c0d8ad98bed3/resourcegroups/kat-vn-aks/providers/Microsoft.ManagedIdentity/userAssignedIdentities/kat-vn-aks-opr-id
        microsoft.containerinstance.virtualnode.injectdns: "false"
    spec:
      containers:
        - image: "mcr.microsoft.com/aci/skr:2.7"
          imagePullPolicy: Always
          name: skr
          resources:
            limits:
              cpu: 2250m
              memory: 2256Mi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: Port
              value: "9000"
          volumeMounts:
            - mountPath: /opt/confidential-containers/share/kata-containers/reference-info-base64
              name: endorsement-location
          command:
            - /skr.sh
        - name: uid2-operator
          image: "ghcr.io/iabtechlab/uid2-operator:5.47.71-alpha-215-SNAPSHOT-azure-cc"
          resources:
            limits:
              memory: "8Gi"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          env:
            - name: VAULT_NAME
              value: kat-vn-aks-vault
            - name: OPERATOR_KEY_SECRET_NAME
              value: kat-vn-aks-opr-key-name
            - name: DEPLOYMENT_ENVIRONMENT
              value: integ
          ports:
            - containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ops/healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: endorsement-location
          hostPath:
            path: /opt/confidential-containers/share/kata-containers/reference-info-base64
      nodeSelector:
        virtualization: virtualnode2
      tolerations:
      - effect: NoSchedule
        key: virtual-kubelet.io/provider
        operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: operator-svc
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
