name: Build UID2 and EUID AMIs
run-name: Build UID2 and EUID AMIs for Operator Release ${{ inputs.operator_release }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      operator_run_number:
        description: The Operator run number. Ignored if Release Number specified.
        type: string

jobs:
  buildUID2:
    name: UID2 Operator AMI
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.buildAMI.outputs.version_number }}
    steps:
      # - name: Pre-cleanup
      #   shell: bash
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #     echo "Cleaning up previous run"
      #     sudo rm -rf * || true
      #     docker stop $(docker ps -aq) || true
      #     docker rm $(docker ps -aq) || true
      #     docker rmi $(docker images -q) || true

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: us-east-1
      #     role-to-assume: arn:aws:iam::072245134533:role/github-runner-build-ami

      - name: Build UID2 Operator AMI
        id: buildAMI
        uses: .github/actions/build_ami
        with:
          identity_scope: uid2
          operator_run_number: ${{ inputs.operator_run_number }}
      
