name: UID2 Scheduled Workflow Status Summary

on:
  schedule:
    - cron: '0 16 * * *'  # 9:00 AM GMT -7
    - cron: '0 0 * * *'   # 5:00 PM GMT -7
  workflow_dispatch:
  push:

jobs:
  check-status:
    runs-on: ubuntu-latest

    env:
      WORKFLOWS: |
        IABTechLab/uid2-operator:publish-all-operators.yaml
        IABTechLab/uid2-operator:vulnerability-scan-failure-notify.yaml

    steps:
      - name: Check workflows and format Slack message
        id: gather
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CROSS_REPO_PAT }}
          script: |
            const workflows = process.env.WORKFLOWS.trim().split('\n');
            let summary = "*📋 UID2 Scheduled Workflow Summary:*\n";

            for (const wf of workflows) {
              const [fullRepo, workflowFile] = wf.trim().split(":");
              const [owner, repo] = fullRepo.trim().split("/");

              console.log(`🔍 Checking ${owner}/${repo} – ${workflowFile}`);

              try {
                // Try to fetch the human-readable workflow name
                let workflowName = workflowFile;
                try {
                  const { data: workflowMeta } = await github.rest.actions.getWorkflow({
                    owner,
                    repo,
                    workflow_id: workflowFile.trim()
                  });
                  workflowName = workflowMeta.name;
                } catch (metaErr) {
                  console.warn(`⚠️ Could not fetch workflow name for ${workflowFile}: ${metaErr.message}`);
                }

                // Fetch workflow runs
                const { data: runs } = await github.rest.actions.listWorkflowRuns({
                  owner,
                  repo,
                  workflow_id: workflowFile.trim(),
                  per_page: 10,
                });

                const run = runs.workflow_runs.find(r => r.event === 'schedule');

                if (run) {
                  const status = run.conclusion === 'success' ? '✅ Success' :
                                 run.conclusion === 'failure' ? '❌ Failed' :
                                 `⚠️ ${run.conclusion}`;
                  summary += `• *${workflowName}* – \`${workflowFile}\` - ${status} (<${run.html_url}|view>)\n`;
                } else {
                  summary += `• *${workflowName}* – \`${workflowFile}\` - ⚠️ No scheduled run found\n`;
                }

              } catch (err) {
                summary += `• \`${repo}/${workflowFile}\` - ❗ Error: ${err.message}\n`;
              }
            }

            core.setOutput("summary", summary);

      - name: Print summary
        run: echo "${{ steps.gather.outputs.summary }}"
