name: UID2 Scheduled Workflow Status Summary

on:
  schedule:
    - cron: '0 16 * * *'  # 9:00 AM GMT -7
    - cron: '0 0 * * *'   # 5:00 PM GMT -7
  workflow_dispatch:
  push:

jobs:
  check-status:
    runs-on: ubuntu-latest

    env:
      WORKFLOWS: |
        IABTechLab/uid2-operator:publish-all-operators.yaml
        IABTechLab/uid2-operator:vulnerability-scan-failure-notify.yaml
        IABTechLab/uid2-core:vulnerability-scan-failure-notify.yaml

    steps:
      - name: Check workflows and format Slack message
        id: gather
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CROSS_REPO_PAT }}
          script: |
            const workflows = process.env.WORKFLOWS.trim().split('\n');

            // group by repo
            const resultsByRepo = {};

            for (const wf of workflows) {
              const [fullRepo, workflowFile] = wf.trim().split(":");
              const [owner, repo] = fullRepo.trim().split("/");

              const key = `${owner}/${repo}`;
              if (!resultsByRepo[key]) {
                resultsByRepo[key] = [];
              }

              try {
                // Try to fetch the workflow metadata
                let workflowName = workflowFile;
                try {
                  const { data: workflowMeta } = await github.rest.actions.getWorkflow({
                    owner,
                    repo,
                    workflow_id: workflowFile.trim()
                  });
                  workflowName = workflowMeta.name;
                } catch (metaErr) {
                  console.warn(`⚠️ Could not fetch workflow name for ${workflowFile}: ${metaErr.message}`);
                }

                const { data: runs } = await github.rest.actions.listWorkflowRuns({
                  owner,
                  repo,
                  workflow_id: workflowFile.trim(),
                  per_page: 10,
                });

                const run = runs.workflow_runs.find(r => r.event === 'schedule');

                if (run) {
                  const status = run.conclusion === 'success' ? '✅ Success' :
                                run.conclusion === 'failure' ? '❌ Failed' :
                                `⚠️ ${run.conclusion}`;
                  resultsByRepo[key].push(`• *${workflowName}* – \`${workflowFile}\` - ${status} (<${run.html_url}|view>)`);
                } else {
                  resultsByRepo[key].push(`• *${workflowName}* – \`${workflowFile}\` - ⚠️ No scheduled run found`);
                }

              } catch (err) {
                resultsByRepo[key].push(`• \`${workflowFile}\` - ❗ Error: ${err.message}`);
              }
            }

            let summary = "*📋 UID2 Scheduled Workflow Summary:*\n";

            for (const [repoName, messages] of Object.entries(resultsByRepo)) {
              summary += `\n🔹 *${repoName}*\n`;
              for (const msg of messages) {
                summary += msg + '\n';
              }
            }

            core.setOutput("summary", summary);
            
      - name: Print summary to console
        run: |
          printf "%s\n" "${{ steps.gather.outputs.summary }}"

      - name: Post summary to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "${{ steps.gather.outputs.summary }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
