name: E2E GCP OIDC Enclave
on:
  [ push ]

env:
  REGISTRY: ghcr.io

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          # git-restore-mtime requires full git history. The default fetch-depth value (1) creates a shallow checkout.
          fetch-depth: 0

      - name: Log in to the Docker container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # we use personal access token here since we need to pull images from private repo (core)
          password: ${{ secrets.GHCR_PAT }}

      - name: Bring up dependencies
        run: |
          echo --- Start docker-compose ---
          docker compose -f ./e2e/docker-compose.yml up -d
          echo --- Finished docker-compose ---

      - name: Check core service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:8088/ops/healthcheck
          max-attempts: 5
          retry-delay: 5s
