name: E2E AZURE CC Enclave
on:
  workflow_dispatch:
    inputs:
      operator_image_version:
        description: 'The version of GCP enclave image'
        type: string
        required: true
      core_image_version:
        description: 'The version of UID2 core image'
        type: string
        default: '2.15.0-50d596678a-default'
      optout_image_version:
        description: 'The version of UID2 optout image'
        type: string
        default: '2.6.18-60727cf243-default'

env:
  REGISTRY: ghcr.io

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3

      - name: Checkout uid2-core repo
        uses: actions/checkout@v3
        with:
          repository: IABTechLab/uid2-core
          token: ${{ secrets.GHCR_PAT }}
          path: core

      - name: Checkout uid2-optout repo
        uses: actions/checkout@v3
        with:
          repository: IABTechLab/uid2-optout
          token: ${{ secrets.GHCR_PAT }}
          path: optout

      - name: Bring up ngrok
        id: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          cd ./e2e && bash ./setup_ngrok.sh

      - name: Log in to the Docker container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # we use personal access token here since we need to pull images from private repo (core)
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare conf files
        env:
          CORE_ROOT: '../core'
          OPTOUT_ROOT: '../optout'
        run: |
          cd ./e2e && bash ./prepare_conf.sh

      - name: Generate Azure enclave deployment artifacts
        id: artifacts
        env:
          IMAGE_VERSION: ${{ inputs.operator_image_version }}
        run: |
          cd ./e2e && bash ./prepare_azure_cc_artifacts.sh

      - name: Prepare Azure enclave metadata
        id: metadata
        env:
          OUTPUT_POLICY_DIGEST_FILE: ${{ steps.artifacts.outputs.OUTPUT_POLICY_DIGEST_FILE }}
        run: |
          cd ./e2e && bash ./prepare_azure_cc_enclave_metadata.sh

      - name: Bring up docker compose
        id: docker_compose
        env:
          NGROK_URL_LOCALSTACK: ${{ steps.ngrok.outputs.NGROK_URL_LOCALSTACK }}
          NGROK_URL_CORE: ${{ steps.ngrok.outputs.NGROK_URL_CORE }}
          NGROK_URL_OPTOUT: ${{ steps.ngrok.outputs.NGROK_URL_OPTOUT }}
          CORE_VERSION: ${{ inputs.core_image_version }}
          OPTOUT_VERSION: ${{ inputs.optout_image_version }}
        run: |
          cd ./e2e && bash ./start_docker.sh

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start Azure private operator
        id: start_azure
        env:
          NGROK_URL_CORE: ${{ steps.ngrok.outputs.NGROK_URL_CORE }}
          NGROK_URL_OPTOUT: ${{ steps.ngrok.outputs.NGROK_URL_OPTOUT }}
          OUTPUT_TEMPLATE_FILE: ${{ steps.artifacts.outputs.OUTPUT_TEMPLATE_FILE }}
          OUTPUT_PARAMETERS_FILE: ${{ steps.artifacts.outputs.OUTPUT_PARAMETERS_FILE }}
        run: |
          cd ./e2e && bash ./start_azure_cc_enclave.sh

      - name: Stop Azure private operator
        if: always()
        env:
          CONTAINER_GROUP_NAME: ${{ steps.start_azure.outputs.CONTAINER_GROUP_NAME }}
        run: |
          cd ./e2e && bash ./stop_azure_cc_enclave.sh

      - name: Stop ngrok
        if: always()
        run: |
          killall ngrok
