name: Publish Public Operator
run-name: ${{ format('Publish {0} Public Operator', inputs.release_type) }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot
      version_number_input:
        description: If set, the version number will not be incremented and the given number will be used.
        type: string
        default: ''
  workflow_call:
    inputs:
      release_type:
        description: The type of version number to return. Must be one of [Snapshot, Patch, Minor or Major]
        required: true
        type: string
      version_number_input:
        description: If set, the version number will not be incremented and the given number will be used.
        type: string
        default: ''
      
    outputs:
      image_tag:
        description: The tag used to describe the image in docker
        value: ${{ jobs.Image.outputs.image_tag }}
  
jobs:
  Image:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-docker-versioned.yaml@v2.2.1
    with: 
      release_type: ${{ inputs.release_type }}
      version_number_input: ${{ inputs.version_number_input }}
      cloud_provider: 'default'
      force_release: 'no' #do not create a release for the component builds, will be created by the parent
    secrets: inherit

  E2E:
    uses: ./.github/workflows/run-e2e-tests-on-operator.yaml
    needs: Image
    with:
      operator_image_version: ${{ needs.Image.outputs.image_tag }}
      operator_root: './'
    secrets: inherit

  Artifacts:
    runs-on: ubuntu-latest
    needs: E2E
    steps:
      - name: collect artifacts
        run: |
          mkdir -p image_details
          IMAGE_TAG=${{ needs.Image.outputs.image_tag }}
          IMAGE=$(jq -n --arg img "$IMAGE_TAG" '{image_tag: $img}')
          echo $IMAGE > image_details/image.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image_details
          path: image_details/
