name: Kat test pipeline
run-name: ${{ format('Kat test pipeline{0} {1} Release', ':', inputs.release_type) }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
          - Major
          - Minor
          - Patch
          - Snapshot
  pull_request:

jobs:
  start:
    name: Start Operator Build
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Show Context
        run: |
          printenv
          echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
