name: Test Call Remote
on: [workflow_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - name: Deploy Your Service
      uses: adityakar/workflow-dispatcher@master
      with:
        owner: UnifiedID2
        repo: aws-operator-building
        token: ${{ secrets.REMOTE_REPO_PAT }}
        event_type: doc_update
        client_payload: '{"git-ref": "${{ github.event.inputs.git-ref }}", "AUTHOR": "${{ github.actor }}", "REVISION": "4"}'
        wait_time: 5
        max_time: 180