name: Validate Docker Image
on:
  workflow_dispatch:
      failure_severity:
        description: 'Must be one of CRITICAL, HIGH, MEDIUM'
        required: false
        default: 'CRITICAL'
        type: string
  schedule:
    - cron: '0 20 * * *'
  push:

env:
  failure: ${{ inputs.failure_severity || 'HIGH' }}

jobs:
  build-publish-docker-default:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-validate-image.yaml@tjm-UID2-577-nightly-scan-image
    with: 
      failure_severity: ${{ env.failure }}
      cloud_provider: 'default'
    secrets: inherit
  build-publish-docker-aws:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-validate-image.yaml@tjm-UID2-577-nightly-scan-image
    with: 
      failure_severity: ${{ env.failure }}
      cloud_provider: 'aws'
    secrets: inherit
  build-publish-docker-gcp:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-validate-image.yaml@tjm-UID2-577-nightly-scan-image
    with: 
      failure_severity: ${{ env.failure }}
      cloud_provider: 'gcp'
    secrets: inherit
